# Generated by Django 5.1.3 on 2024-11-09 05:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('index_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['index_order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('index_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['index_order'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_us', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Phone number with country code i.e. 917990577979', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, default='', null=True)),
                ('instagram', models.URLField(blank=True, default='', null=True)),
                ('youtube', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('index_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['index_order'],
            },
        ),
    ]
