# Generated by Django 5.1.3 on 2024-11-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='google_maps',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
